Assignment6/Models/BO/Assignment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Assignment6.Models.BO
{
    public class Assignment
    {
        public int AssignmentId { get; set; }
        public string Title { get; set; }
        public string Deadline { get; set; }
        public string DisplayName { get; set; }
        public string ProblemLink { get; set; }
        public string DifficultyLevel { get; set; }
        public int Marks { get; set; }
        public string Format { get; set; }
        public string Solution { get; set; }
        public string CourseCode { get; set; }
    }
}

Assignment6/Controllers/TeacherHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Assignment6.Models.BO;
using Assignment6.Models.DAL;

namespace Assignment6.Controllers
{
    public class TeacherHomeController : Controller
    {
        //
        // GET: /Teacher/


        public ActionResult Index()
        {
            User u = (User)Session["user"];
            List<Course> list = CourseDAL.getAllTeacherCourses(u.UserId);
            return View(list);
        }

        [HttpGet]
        public ActionResult Assignments(string id)
        {
            //ViewData["course"] = id;
           // ViewBag.course = id;


            Session["course"] = id;
            List<Assignment> list = AssignmentDAL.getCourseAssignments(id);
            return View("Assignments" , list);
        }
        [HttpGet]
        public ActionResult LogOut()
        {
            Session.Clear();
            return View("~/Views/Home/Login.cshtml");
        }
        public ActionResult CreateNewAssignment()
        {
          
            return View("CreateNewAssignment");
        }

        [HttpGet]
        public ActionResult AssignmentDetails(int id)
        {
            List<Submission> list = SubmissionDAL.getAssignmentSubmissions(id);
            Session["assignment"] = id;
            return View(list);
        }
        //string AssTitle , string AssName , string AssLevel , string AssMarks , string AssFormat , string AssDeadline
        [HttpPost]
        public ActionResult saveNewAssignment( Assignment a  )
        {
            var uniqueness = "";
            var fileSavePath="";
            if (Request.Files["ProblemLink"] != null)
            {
                var file = Request.Files["ProblemLink"];
                if (file.FileName != "")
                {
                    var ext = System.IO.Path.GetExtension(file.FileName);
                    uniqueness = Guid.NewGuid().ToString()+ext;
                    var rootPath = Server.MapPath("~/Assignments");
                    fileSavePath = System.IO.Path.Combine(rootPath , uniqueness );
                    file.SaveAs(fileSavePath);
                }
                a.ProblemLink= fileSavePath;
                a.CourseCode = Session["course"].ToString();
                AssignmentDAL.insert(a);
            }
            String id = Session["course"].ToString();
            List<Assignment> list = AssignmentDAL.getCourseAssignments(id);
            return View("Assignments", list);
           // return View("Assignments");
        }
       
        [HttpPost]
        public ActionResult insertCourse( Course course)
        {

           Object data = null;
           User u =  (User)Session["user"];
           course.InstructorId = u.UserId;
           int r = CourseDAL.insert(course);

         
 

           List<Course> list = CourseDAL.getAllTeacherCourses(u.UserId);
           return View("Index", list);

          // return Json(data, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Download(int id)
        {

            Session.Add("submission" , id);
            Submission sub = SubmissionDAL.getSpecificSubmission(id);
            string fullName = sub.Link;
            string extension = getExtension(fullName);
            byte[] fileBytes = GetFile(fullName);
            string fileName = sub.DisplayName+"."+extension;
            return File(
                fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }
        string getExtension(string fileName)
        {
            String[] str = fileName.Split('.');
            return str[str.Length - 1];
        }

        byte[] GetFile(string s)
        {
            System.IO.FileStream fs = System.IO.File.OpenRead(s);
            byte[] data = new byte[fs.Length];
            int br = fs.Read(data, 0, data.Length);
            if (br != fs.Length)
                throw new System.IO.IOException(s);
            return data;
        }
        
        //
        //  GET: /Teacher/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Teacher/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Teacher/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Teacher/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Teacher/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Teacher/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Teacher/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Assignment6/Views/TeacherHome/AssignmentDetails.cshtml
@model List<Assignment6.Models.BO.Submission>
@{
    ViewBag.Title = "AssignmentDetails";
    Layout = "~/Views/Shared/View1.cshtml";
}

<h2 align="center">Assignment Submissions and  Details</h2>


    
 @*@Html.ActionLink(d.DisplayName , "AssignmentDetails", "TeacherHome", new { id = d.AssignmentId }, d.AssignmentId);*@
<table>
        <th>Solution
            </th>
        <th>Submission Time
            </th>
         @foreach(var d in Model)
         {
             <tr>
                 <td>
                  @Html.ActionLink(d.DisplayName , "Download", "TeacherHome", new { id = d.Id}, d.Id)
                     </td>
                 </tr>
             <tr><td>@d.SubmissionTime</td></tr>
         }
  

</table>

Assignment6/Views/TeacherHome/Assignments.cshtml
@model List<Assignment6.Models.BO.Assignment>
@{
    ViewBag.Title = "Assignments";
    Layout = "~/Views/Shared/View1.cshtml";
}


<h2 align="center">Assignments</h2>

<table>

@{   
foreach (var d in Model){
     <tr>
        <td>
    
 @Html.ActionLink(d.DisplayName , "AssignmentDetails", "TeacherHome", new { id = d.AssignmentId }, d.AssignmentId)
 </td>

        @* <td>  
             @d.DisplayName</td>*@
             </tr>

}
}
    </table>
<input type="submit" , id="btnNew" , value="Create New Assignment", class="spebtn">


@*Assignment Title <input type="text" , id="AssTitle">
<br/>
Assignment Display Name <input type="text" , id="AssName">
<br/>
Difficulty Level <input type="text" , id="AssLevel">
<br/>
Total Marks <input type="number" , id="AssMarks">
<br/>
Format <input type="text" , id="AssFormat">
<br/>
Deadline <input type="datetime" , id="AssDeadline">
<br/>
Upload File <input type="file" , id="AssFile">
<br/>*@

@*<div class="table-responsive">
        <input type="text" id="Name" />
        <input type="text" id="Address" />
        <button onclick="OpenDialog()">
            Open Dialog</button>
</div>
<div id="Dialog-Box">
        <input type="text" id="Dialog-Name" />
        <input type="text" id="Dialog-Address" />
        <input type="submit" onclick="onsave()" value="save" />
 </div>*@

@section scripts{


    
    <script>
        $(function () {
            $("#btnNew").click(function () {


               // alert("Clicked");
                location.href = "/TeacherHome/CreateNewAssignment";
                return false;
            }
            );
        });
        </script>

}

Assignment6/Views/TeacherHome/CreateNewAssignment.cshtml
@{
    ViewBag.Title = "CreateNewAssignment";
    Layout = "~/Views/Shared/View1.cshtml";
}



<div class="f">
    <h2 align="center">Create New Assignment</h2>

<form action="/TeacherHome/saveNewAssignment" , method="post" , enctype="multipart/form-data">

Assignment Title <input type="text" , id="Title" , name="Title" ,class="search">
<br/>
Assignment Display Name <input type="text" , id="AssName" name="DisplayName" , class="search">
<br/>
Difficulty Level <input type="text" , id="AssLevel" , name="DifficultyLevel" , class="search">
<br/>
Total Marks <input type="number" , id="AssMarks" , name="Marks" , class="search">
<br/>
Format <input type="text" , id="AssFormat" , name="Format" , class="search">
<br/>
Deadline <input type="datetime" , id="AssDeadline" , name="Deadline" , class="search">
<br/>
Upload File <input type="file" , id="AssFile" , name="ProblemLink" , class="search">
<input type="submit" , value="Create" , class="btn">
    </form>
    </div>

Assignment6/Views/TeacherHome/Index.cshtml
@model List<Assignment6.Models.BO.Course>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/View1.cshtml";
}

<h2>Welcome Teacher</h2>
 <h2>Teaching Courses</h2>


@*<form action="/TeacherHome/LogOut" , method="get" , enctype="multipart/form-data" >
<input type="submit" , id="stLogOut" , value="Log out", class="btn">
    </form>*@

    
<table>  
  
    <tr>  
        <th>Course Title</th>  
         <th>Course Code</th>   
      
    </tr> 
        
    
    @foreach (var d in Model)  
    {  
        <tr>  
            <td>
          @*  <td><a id="abc" href="/TeacherHome/CreateNewAssignment"> @d.CourseTitle</a></td>  *@
             
           @Html.ActionLink(d.CourseTitle, "Assignments", "TeacherHome", new { id = d.CourseCode}, d.CourseCode)

           @* <td>@d.FirstName</td>  
            <td>@d.LastName</td>  
            <td>@d.Email</td>  
            <td>@d.Salary</td>  
            <td>@d.Company</td>  
            <td>@d.Dept</td>  
  *@ </td>
            <td>@d.CourseCode</td>
        </tr>  
    }  
        
</table>  

<div class="course">
 <h1 align="center">Create new course</h1>
<form action="/TeacherHome/insertCourse" , method="post" enctype="multipart/form-data">
Course Title: <input type="text" , id="CourseTitle" , name="CourseTitle" , class="search">
<br/>
Credit Hours: <input type="text" , id="CreditHours" , name="CreditHours" , class="search">
<br/>

<input type="submit" id="btnCreateCourse" value="Create Course" , class="btn" >
    </form>
    </div>

<form action="/TeacherHome/LogOut" , method="get" , enctype="multipart/form-data" >
<input type="submit" , id="stLogOut" , value="Log out", class="lbtn">
    </form>
@section scripts
{
    <script>
       
        //$(function () {
        //    $("#abc").click(function (s) {
            
              
        //        alert("yaaaaaaaaaaaaa");
        //    }
        //        );


        //    $("#btnCreateCourse").click(function () {

                
        //        var title = $("#txtCourseTitle").val();
        //        var hours = $("#txtCreditHours").val();
        //        ////var u = new Object();
        //        ////u.CourseTitle = login;
        //        ////u.CreditHours = hours;
          
        //        var data1 = { "CourseTitle": title, "CreditHours": hours }
        //        var settings = {
        //            type: "POST",
        //           dataType: "json",
        //            url: "/TeacherHome/insertCourse",
        //            data: JSON.stringify({ "course": data1 }),
        //            contentType: false,
        //            processData: false,
        //            tradition: true,
        //            contentType: "application/json; charset=utf-8",
        //            succuss: function (response) {
        //            },
        //            error: function () {
        //                alert("Severe error");
        //            },

        //            complete: function (response, textStatus) {
        //                 var x = JSON.parse(response.responseText);
        //                //var x = response.responseText;
        //                alert(response + "   " + textStatus + "  " + response.responseText + "muzna "+ x.res);
        //                if (x.res > 0) {
                            
        //                    alert("Course created succussfully");
        //                   // location.href = "/TeacherHome/Index";
        //                }

        //               //else if (x.res == "Student") {

        //               //     location.href = "/StudentHome/Index";
        //               // }
        //                //else if(x.res== 1)
        //                //    alert("Email and Password does not match");
        //                //else if (x.res == -1)
        //                //    alert("Email does not exist");
        //                else
        //                    alert("Course not created");
        //                console.log(response.res);
        //            }
        //        }
        //        //if (s=="succuss") {
                    
        //        $.ajax(settings);
        //        //}
        //        //else
        //          //  alert(s);
        //            return false;
             
        //        });
        //    });
       
    
        </script>
    }