Assignment6/Models/BO/Assignment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Assignment6.Models.BO
{
    public class Assignment
    {
        public int AssignmentId { get; set; }
        public string Title { get; set; }
        public string Deadline { get; set; }
        public string DisplayName { get; set; }
        public string ProblemLink { get; set; }
        public string DifficultyLevel { get; set; }
        public int Marks { get; set; }
        public string Format { get; set; }
        public string Solution { get; set; }
        public string CourseCode { get; set; }
    }
}

Assignment6/Controllers/StudentHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Assignment6.Models.BO;
using Assignment6.Models.DAL;
using System.IO;


namespace Assignment6.Controllers
{
    public class StudentHomeController : Controller
    {
        //
        // GET: /StudentHome/

        public ActionResult Index()
        {
            User u = (User)Session["user"];
          
            List<Course> list = StudentCourseDAL.getAllStudentCourses(u.UserId);
            return View("index", list);
        }
           [HttpPost]
        public ActionResult insertStudentCourse(string courseId)
        {
            User u = (User)Session["user"];
            StudentCourseDAL.insert(u.UserId , courseId);
            List<Course> list = StudentCourseDAL.getAllStudentCourses(u.UserId);
            return View("index" , list);
        }
           [HttpGet]
           public ActionResult Assignments(string id)
           {
               //ViewData["course"] = id;
               // ViewBag.course = id;


               Session["course"] = id;
               List<Assignment> list = AssignmentDAL.getCourseAssignments(id);
               return View("Assignments", list);
           }

           public ActionResult submitAssignment(Submission sub)
           {
               //Session["assignment"] = id;
               //User u = (User)Session["user"];
               //Submission sub = SubmissionDAL.getSubmissionOfSepeificSubmiiterAndAssignment(id, u.UserId);

               int id =  (int)Session["assignment"] ;
               User u = (User)Session["user"];

                 Submission s = SubmissionDAL.getSubmissionOfSepeificSubmiiterAndAssignment(id , u.UserId);
                 if (s.Id == 0)
                 {

                     //User u = (User)Session["user"];
                     sub.SubmitterId = u.UserId;
                     sub.DisplayName = u.Name;
                     //  Assignment a = (Assignment)Session["assignment"]);
                     sub.AssignmentId = Convert.ToInt32(Session["assignment"].ToString());


                     var uniqueness = "";
                     var fileSavePath = "";
                     if (Request.Files["Link"] != null)
                     {
                         var file = Request.Files["Link"];
                         if (file.FileName != "")
                         {
                             var ext = System.IO.Path.GetExtension(file.FileName);
                             uniqueness = Guid.NewGuid().ToString() + ext;
                             var rootPath = Server.MapPath("~/Submissions");
                             fileSavePath = System.IO.Path.Combine(rootPath, uniqueness);
                             file.SaveAs(fileSavePath);
                         }
                         sub.Link = fileSavePath;

                     }
                     SubmissionDAL.insert(sub);
                 }
              
             //  Session.Add( sub.Id.ToString() , "ok");

               return View("submissionSubmitted");
           }

           public ActionResult submissionSubmitted()
           {
               return View();
           }

   public ActionResult AssignmentSubmission(int id)
           {
               Session["assignment"] = id;
               User u =(User) Session["user"];
               Submission sub = SubmissionDAL.getSubmissionOfSepeificSubmiiterAndAssignment(id , u.UserId);
               if (sub.Id == 0)
                   return View("submitAssignment");
             //  Session.Add(sub.Id.ToString(), "ok");
               else

               return View("submissionSubmitted");
           }
            [HttpGet]
           public ActionResult Download()
           {
               int id = (int)Session["assignment"];
             
               Assignment ass = AssignmentDAL.getSpecificAssignment(id);
               string fullName = ass.ProblemLink;
               string extension = getExtension(fullName);
               byte[] fileBytes = GetFile(fullName);
               string fileName = ass.DisplayName+"."+extension;
               return File(
                   fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
           }
            string getExtension(string fileName)
            {
                String[] str = fileName.Split('.');
                return str[str.Length - 1];
            }


           byte[] GetFile(string s)
           {
               System.IO.FileStream fs = System.IO.File.OpenRead(s);
               byte[] data = new byte[fs.Length];
               int br = fs.Read(data, 0, data.Length);
               if (br != fs.Length)
                   throw new System.IO.IOException(s);
               return data;
           }
        [HttpGet]
           public ActionResult LogOut()
           {
               Session.Clear();
               return View("~/Views/Home/Login.cshtml");
           }

        //
        // GET: /StudentHome/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /StudentHome/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /StudentHome/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /StudentHome/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /StudentHome/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /StudentHome/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /StudentHome/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Assignment6/Views/StudentHome/Assignments.cshtml
@model List<Assignment6.Models.BO.Assignment>
@{
    ViewBag.Title = "Assignments";
    Layout = "~/Views/Shared/View1.cshtml";
}


<h1 align="center" >Assignments</h1>
<table>

@{   
foreach (var d in Model){
     <tr>
        <td>
    
 @Html.ActionLink(d.DisplayName , "AssignmentSubmission", "StudentHome", new { id = d.AssignmentId }, d.AssignmentId)
 </td>

        @* <td>  
             @d.DisplayName</td>*@
             </tr>

}
}
    </table>


@*Assignment Title <input type="text" , id="AssTitle">
<br/>
Assignment Display Name <input type="text" , id="AssName">
<br/>
Difficulty Level <input type="text" , id="AssLevel">
<br/>
Total Marks <input type="number" , id="AssMarks">
<br/>
Format <input type="text" , id="AssFormat">
<br/>
Deadline <input type="datetime" , id="AssDeadline">
<br/>
Upload File <input type="file" , id="AssFile">
<br/>*@

@*<div class="table-responsive">
        <input type="text" id="Name" />
        <input type="text" id="Address" />
        <button onclick="OpenDialog()">
            Open Dialog</button>
</div>
<div id="Dialog-Box">
        <input type="text" id="Dialog-Name" />
        <input type="text" id="Dialog-Address" />
        <input type="submit" onclick="onsave()" value="save" />
 </div>*@

@section scripts{


    
    <script>
        $(function () {
            $("#btnNew").click(function () {


             //   alert("Clicked");
                location.href = "/TeacherHome/CreateNewAssignment";
                return false;
            }
            );
        });
        </script>

}

Assignment6/Views/StudentHome/Index.cshtml
@model List<Assignment6.Models.BO.Course>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/View1.cshtml";
}

<h2>Welcome Student</h2>


        <h2>Enrolled Courses</h2>

<table>  
    <tr>  
        <th>Course Title</th>  
         <th>Course Code</th>  
      
    </tr>  
    @foreach (var d in Model)  
    {  
        <tr>  
            <td>
       
             
           @Html.ActionLink(d.CourseTitle, "Assignments", "StudentHome", new { id = d.CourseCode}, d.CourseCode)

          </td>

              <td>@d.CourseCode</td>
        </tr>  
    }  
</table>  
<div class="course">
    <h1 align="center">Enroll in Course</h1>
<form action="/StudentHome/insertStudentCourse" , method="post" enctype="multipart/form-data">
Enter Course Code (Provided by your instructor): <input type="text" , id="txtCourseTitle" , name="courseId" ,  class="search">
<br/>

<input type="submit" id="btnCreateCourse" value="Enroll in a Course" , class="btn">

    </form>

    </div>


<form action="/StudentHome/LogOut" , method="get" , enctype="multipart/form-data" >
<input type="submit" , id="stLogOut" , value="Log out", class="lbtn">
    </form>
    

@section scripts
{
    <script>
       
    
    
        </script>
    }

Assignment6/Views/StudentHome/submissionSubmitted.cshtml
@{
    ViewBag.Title = "submissionSubmitted";
    Layout = "~/Views/Shared/View1.cshtml";
}


<h2>You have succussfully submitted your assignment</h2>
<br/>
<h2>Note: Resubmissions not allowed</h2>

Assignment6/Views/StudentHome/submitAssignment.cshtml
@*@model Assignment6.Models.BO.Submission*@
@{
    ViewBag.Title = "submitAssignment";
    Layout = "~/Views/Shared/View1.cshtml";
}

<form action="/StudentHome/Download" , method="get" , enctype="multipart/form-data" >
<input type="submit" , id="download" , value="Download Assignment", class="btn">
    </form>


<div class="f">
    <h1 align="center">Submit Assignment</h1>
<form action="/StudentHome/submitAssignment" , method="post" , enctype="multipart/form-data">
Submit Assignment<input type="file" name="Link" ,  , class="search">
    <input type="submit" , value="Upload" , id="btnSubmit" , class="btn">
  </form>
    </div>

@*@{
    if(Model != null){
        int id = Model.Id;
        
        if(id!=0){
            String s = id.ToString();
        if( Session[s] == "ok")
        {
            <h1>Submitted</h1>
        }
        }
    }
}*@


@section scripts
{
    <script>
       
        //$(function () {
          

        //    $("#btnSubmit").click(function () {

                
        //        //var title = $("#txtCourseTitle").val();
        //        //var hours = $("#txtCreditHours").val();
        //        ////var u = new Object();
        //        ////u.CourseTitle = login;
        //        ////u.CreditHours = hours;
          
        //        //var data1 = { "CourseTitle": title, "CreditHours": hours }
        //        var data1 = {}

        //        var settings = {
        //            type: "POST",
        //           dataType: "json",
        //            url: "/StudentHome/SubmitAssignment",
        //            data: JSON.stringify({ "sub": data1 }),
        //            contentType: false,
        //            processData: false,
        //            tradition: true,
        //            contentType: "application/json; charset=utf-8",
        //            succuss: function (response) {
        //            },
        //            error: function () {
        //                alert("Severe error");
        //            },

        //            complete: function (response, textStatus) {
        //                 var x = JSON.parse(response.responseText);
        //                //var x = response.responseText;
        //                alert(response + "   " + textStatus + "  " + response.responseText + "muzna "+ x.res);
        //                if (x.res > 0) {
                            
        //                    alert("Assignment submitted succussfully");
        //                   // location.href = "/TeacherHome/Index";
        //                }

        //               //else if (x.res == "Student") {

        //               //     location.href = "/StudentHome/Index";
        //               // }
        //                //else if(x.res== 1)
        //                //    alert("Email and Password does not match");
        //                //else if (x.res == -1)
        //                //    alert("Email does not exist");
        //                else
        //                    alert("Assignment not Submitted");
        //                console.log(response.res);
        //            }
        //        }
        //        //if (s=="succuss") {
                    
        //        $.ajax(settings);
        //        //}
        //        //else
        //          //  alert(s);
        //            return false;
             
        //        });
        //    });
       
    
        </script>
    }